export const routes = {
  home: "/",
  login: "/login",
  saasLogin: "/saas/login",
  tenantRegister: "/register-hospital",
  twoFactor: "/two-factor",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",

  dashboard: "/dashboard",
  saasDashboard: "/saas",
  tenants: "/tenants",
  tenantDetail: "/tenants/:tenantId",
  tenantModules: "/tenant-modules",
  tenantDomains: "/tenant-domains",

  patients: "/patients",
  patientRegister: "/patients/register",
  patientSearch: "/patients/search",
  patientDetail: "/patients/:patientId",
  membershipCards: "/patients/membership-cards",
  cardFundingApprovals: "/patients/card-funding",
  
  visits: "/visits",
  visitInitiate: "/visits/initiate",
  visitFlows: "/visits/flows",
  visitDetail: "/visits/:visitId",
  visitReroute: "/visits/:visitId/reroute",

  serviceDeliveryPoints: "/service-delivery-points",
  interoperability: "/interoperability",
  integrations: "/settings/integrations",
  developerAccess: "/settings/developer-access",
  medicalAccess: "/medical-access",
  medicalAccessPatient: "/medical-access/patient",
  medicalAccessView: "/medical-access/view",
  verifyCard: "/verify-card",
  insuranceDashboard: "/insurance/dashboard",
  insurancePayers: "/insurance/payers",
  insuranceEnrollees: "/insurance/enrollees",
  insuranceRemittances: "/insurance/remittances",
  banking: "/accounting/banking",
  cashOffice: "/accounting/cash-office",
  arDocuments: "/accounting/credit-notes",
  financeReportsExt: "/accounting/reports-plus",
  financeSettings: "/accounting/settings",
  statutory: "/accounting/statutory",
  journalEntries: "/accounting/journal-entries",
  generalLedger: "/accounting/ledger",
  financialReports: "/accounting/reports",
  payables: "/accounting/payables",
  fixedAssets: "/accounting/fixed-assets",
  budgets: "/accounting/budgets",
  developerPortal: "/developers",
  facilities: "/facilities",


  
  queues: "/queues",
  queueAnalytics: "/queues/analytics",
  queueDisplayBoard: "/queues/display-board",
  
  clinical: "/clinical",
  triage: "/clinical/triage",
  consultation: "/clinical/consultation",
  vitals: "/clinical/vitals",
  clinicalTemplates: "/clinical/templates",

  laboratory: "/laboratory",
  labOrders: "/laboratory/orders",
  labResults: "/laboratory/results",
  labTests: "/laboratory/tests",

  radiology: "/radiology",
  pharmacy: "/pharmacy",
  pharmacyDispense: "/pharmacy/dispense",

  admissions: "/admissions",
  wards: "/wards",
  beds: "/beds",

  // Surgery / Theatre
  surgery: "/surgery",
  surgeryCase: "/surgery/cases/:caseId",
  theatres: "/surgery/theatres",
  surgicalProcedures: "/surgery/procedures",
  instrumentSets: "/surgery/instruments",
  billing: "/billing",
  billingDetail: "/billing/:invoiceId",
  billableServices: "/billing/services",
  chartOfAccounts: "/billing/accounts",
  payments: "/payments",
  insurance: "/insurance",
  inventory: "/inventory",
  inventoryStores: "/inventory/stores",
  inventoryItems: "/inventory/items",
  inventoryItemDetail: "/inventory/items/:itemId",
  inventoryMovements: "/inventory/movements",
  procurement: "/inventory/procurement",
  drugs: "/drugs",
  appointments: "/appointments",
  doctorCalendar: "/doctor-calendar",
  medicationAdherence: "/medication-adherence",
  
  staff: "/staff",
  hr: "/hr",
  payroll: "/payroll",
  payrollSalary: "/payroll/salary",
  payrollLookups: "/payroll/lookups",
  payrollComponents: "/payroll/components",
  payrollPensionProviders: "/payroll/pension-providers",
  timesheets: "/staff/timesheets",
  staffFinance: "/staff/finance",
  leaveRequests: "/hr/leave",
  myLeave: "/hr/my-leave",
  compliance: "/compliance",
  backups: "/settings/backups",
  tax: "/tax",
  
  approvals: "/approvals",
  approvalFlows: "/approvals/flows",
  approvalRequest: "/approvals/requests/:requestId",
  reports: "/reports",
  settings: "/settings",
  notifications: "/notifications",
  patientMessages: "/patient-messages",
  sendMessage: "/messaging",
  roles: "/roles",
  profile: "/profile",
  hrAttendance: "/hr/attendance",
  hrRoster: "/hr/roster",
  hrStaffRecords: "/hr/staff-records",

  ambulances: "/ambulances",
  ambulanceDetail: "/ambulances/:ambulanceId",

  invitations: "/invitations",
  invitationAccept: "/invitations/accept",

  saasInvoices: "/saas/billing",
  saasPaymentsLookup: "/saas/payments",
  supportAccess: "/saas/support",

  planBilling: "/settings/plan",
  billingCallback: "/billing/callback",
  saasPaymentConfirmations: "/saas/payment-confirmations",
  emailSettings: "/settings/email",
  tenantJobs: "/settings/jobs",
  settingsBranding: "/settings/branding",

  loyalty: "/patients/:patientId/loyalty",
  portalLogin: "/portal/login",
  portalHome: "/portal/home",
  portalAppointments: "/portal/appointments",
  portalNotifications: "/portal/notifications",
  portalLabResults: "/portal/lab-results",
  portalInvoices: "/portal/invoices",
  portalBaselineDiagnostics: "/portal/baseline-diagnostics",
  medicalExams: "/medical-exams",
  portalMessages: "/portal/messages",
  portalProfile: "/portal/profile",
  patientPaymentGateways: "/billing/gateways",
  connectivity: "/saas/connectivity",
} as const;

